version: "3.9"
services:
  database:
    container_name: docker-postgres
    image: postgres
    restart: always
    env_file:
      - shortener.env
    ports:
      - "5432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5 
  url-shortener:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    env_file: shortener.env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: